name: Latency
abbreviation: latency
checker: PragmaRX\Health\Checkers\Ping
notify: true
binary: "{{ config('app.ping.bin') }}"
error_message:
  'The host "%s" exceeded the maximum accepted latency on ping: last ping was %s, accepted is %s'
column_size: 3
targets:
  - server:
      name: webserver alerj
      hostname: www.alerj.rj.gov.br
      accepted_latency: 200
