name: Mailgun Connectable
abbreviation: redisconn
checker: PragmaRX\Health\Checkers\PortCheck
notify: true
column_size: 3
error_message: "Could not connect to %s on port %s"
targets:
  - mailgun1:
      hostname: api.mailgun.net
      port: 443
      timeout: 2
